environment:
  RETHINKDB_HOST: "rethinkdb"
  RETHINKDB_PORT: 28015
  RETHINKDB_NAME: "dbname" # your db name here
  RETHINKDB_USER: "admin"
  RETHINKDB_PASS: ""
  RMQ_HOST: "rabbitmq"
  RMQ_PORT: 5672
  RMQ_USER: "user"
  RMQ_PASS: "pass"
  RMQ_TOPICS: "new-file" # can be comma separated
  RABBITMQ_DEFAULT_USER: "user"
  RABBITMQ_DEFAULT_PASS: "pass"