version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  sample-func:
    lang: python3-sksleton
    handler: ./sample-func
    image: sample-func:latest
    environment_file:
      - config.yml
    build_options:
      - dev
    annotations:
      topic: new-file # your routing-keys to listen to here